import java.util.HashSet;
import java.util.Set;
class Students {

    String name;
    int rollnum ;

    Students(String name  , int rollnum){
        this.name =name;
        this.rollnum = rollnum;
    }

    @Override
    public String toString(){
        return name + " " + rollnum ;
    }
}



public class _13concept {
    public static void main(String[] args) {
        
        Students s1 =new Students("akash", 1);
        Students s2 =new Students("Diven", 2);
        Students s3 =new Students("Harsh", 3);
        Students s4 =new Students("akash", 1);

        Set<Students> sset = new HashSet<Students>();

        sset.add(s1);
        sset.add(s2);
        sset.add(s3);
        sset.add(s4); // s1 and s2 are same but still added , 

        // hashet ko lg raha new h to alg h 
        // so consider s1 and s4 alg alg
        // yha hashcode is generated based on diff diff objects
        // hashcode is generated by equals method of each class wheile using obj in hashset
        // this quals method provided by object class (root class)
        // so , we will oveerride equal method in that class which objs are gonaa passed 

        // and tell eqauls that based on this this members genarate hashscode , not based on objects creatted

        System.out.println(sset);
    }
}



// equals() ,hashCode() both method are of Object class
// which we have to overrirde 
// hashcode() --  for telling on what basis to generate
// equals to generates 



// 2 students are diff when they have 2 diff rolls numbers 