class _2intro {
    public static void main(String[] args) {
        
        // collection fremworks are classes generated by interface 
        // this classes are used to store data in big amount 
        // this are build in data structure provided by java
        // they are highly optimised internally
        // we can also code for making it but it will be hard and will not that much optimised

        // collection fremworks is all interfaces and classes

        // interable is root  interface , then comes collection interface 
        // List (for storing data in continious ) , Set  (to avoid duplicates), Queue (FIFO) are child interfaces for collection , this interfaces separate the data satrutures as per there property 

        // each child interface are implememnted in many classes
        // eg. List interface  --> ArrayList class , LinkedList class , Stack class
        // Set interface--> Hashset class , LinkedHashSet class , TreeSet class
        // Queue interface --- > ArrayQueue class ,LinkedList class ,PriorityQueue class

        // Map is also a interface but not child of Collection interface it is separate interface
        // which implememnted in , HashMap class , TreeMap class LinkedHashMap class 


        // this all classes's object  are data struture only
        // this all classes present in java.util package

    }
}


// this colection frame works classes obj created in some diff syntax